# Github app_id + app_secret, used in initializers/01_oauth.rb

development:
  app_id: c16eef8aa94bc68a8dca
  app_secret: a71d04c7e3952aaabe7415cfdcda938f7db45aea
test:
  app_id: c16eef8aa94bc68a8dca
  app_secret: a71d04c7e3952aaabe7415cfdcda938f7db45aea
production:
  app_id: 49a5545bd36ececafd36
  app_secret: 6253e13cfd5f1c8040ee1dfbdd8dcd9d4110e199
