# Linkedin app_id + app_secret, used in initializers/01_oauth.rb

development:
  app_id: 77ipasuqbpjwx1
  app_secret: b7MeUdBnILxOv6kR
test:
  app_id: 856ae1f6-6b0b-42a0-9401-dc998555a528
  app_secret: 08a19b21-9db1-4658-b855-50c82b5372e6
production:
  app_id: 77dcg9hik0p5bs
  app_secret: FQpWT4uLMngUZaOm
